Issue 403 depricate modelltypes
Informasjonsforvaltning/modelldcat-ap-no pull request #411
Opened 2022-08-31 20:54 UTC by tormodv

Fix #403 

Mappet både liste og de individuelle verdiene

2022-09-15 07:04 UTC, jimjyang requested changes

2022-09-15 07:04 UTC, jimjyang commented on ontology/modelldcatno.ttl
> +                                          <https://data.norge.no/vocabulary/information-model-type#application-model> ;
mangler `dct:isReplacedBy` her

2022-09-15 09:49 UTC, tormodv commented on ontology/modelldcatno.ttl
> +                                          <https://data.norge.no/vocabulary/information-model-type#application-model> ;
Det fikser jeg

2022-09-16 09:26 UTC, tormodv commented on ontology/modelldcatno.ttl
> +                                          <https://data.norge.no/vocabulary/information-model-type#application-model> ;
Lagt til manglende relasjon

2022-09-17 05:16 UTC, jimjyang approved these changes

2022-10-17 13:28 UTC, merged